// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"

// Parameter definitions for Vtop_PropagateOnce__N3_V9_C5
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__PAIRS;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__p;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__p;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__p;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__p;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__id;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__CC;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage4_all_different__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage4_all_different__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__ITERATIONS;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage6_singleton_detection__DOT__N;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage6_singleton_detection__DOT__V;
constexpr IData/*31:0*/ Vtop_PropagateOnce__N3_V9_C5::stage6_singleton_detection__DOT__ID_BITS;


void Vtop_PropagateOnce__N3_V9_C5___ctor_var_reset(Vtop_PropagateOnce__N3_V9_C5* vlSelf);

Vtop_PropagateOnce__N3_V9_C5::Vtop_PropagateOnce__N3_V9_C5() = default;
Vtop_PropagateOnce__N3_V9_C5::~Vtop_PropagateOnce__N3_V9_C5() = default;

void Vtop_PropagateOnce__N3_V9_C5::ctor(Vtop__Syms* symsp, const char* namep) {
    vlSymsp = symsp;
    vlNamep = strdup(Verilated::catName(vlSymsp->name(), namep));
    // Reset structure values
    Vtop_PropagateOnce__N3_V9_C5___ctor_var_reset(this);
}

void Vtop_PropagateOnce__N3_V9_C5::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

void Vtop_PropagateOnce__N3_V9_C5::dtor() {
    VL_DO_DANGLING(std::free(const_cast<char*>(vlNamep)), vlNamep);
}
