// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_PropagateOnce__N3_V9_C5;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_PropagateOnce__N3_V9_C5* __PVT__Brendan3_OneStep__DOT__prop1;
    Vtop_PropagateOnce__N3_V9_C5* __PVT__Brendan3_OneStep__DOT__prop2;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_OUT64(out_colours_top,44,0);
        VL_OUT64(out_colours_right,44,0);
        VL_OUT64(out_colours_bottom,44,0);
        VL_OUT64(out_colours_left,44,0);
        VL_OUT8(out_next_var,3,0);
        VL_OUT8(out_valid,0,0);
        VL_OUT8(out_changed,0,0);
        VL_OUT8(out_deadend,0,0);
        QData/*44:0*/ Brendan3_OneStep__DOT__out_colours_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__out_colours_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__out_colours_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__out_colours_left;
        CData/*3:0*/ Brendan3_OneStep__DOT__out_next_var;
        CData/*0:0*/ Brendan3_OneStep__DOT__out_valid;
        CData/*0:0*/ Brendan3_OneStep__DOT__out_changed;
        CData/*0:0*/ Brendan3_OneStep__DOT__out_deadend;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_elements_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_elements_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_elements_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_elements_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_load_colours_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_load_colours_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_load_colours_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_load_colours_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_prop1_colours_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_prop1_colours_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_prop1_colours_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_prop1_colours_left;
        CData/*3:0*/ Brendan3_OneStep__DOT__w_next_var;
        CData/*0:0*/ Brendan3_OneStep__DOT__w_valid;
        CData/*3:0*/ Brendan3_OneStep__DOT__w_tile_id;
        CData/*1:0*/ Brendan3_OneStep__DOT__w_rotation;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_assign_colours_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_assign_colours_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_assign_colours_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__w_assign_colours_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_elements_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_elements_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_elements_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_elements_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_colours_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_colours_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_colours_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__out_colours_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__out_elements_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__out_elements_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__out_elements_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__out_elements_left;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__9;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__9;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__9;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__9;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__8;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__8;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__8;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__8;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__7;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__7;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__7;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__7;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__6;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__6;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__6;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__6;
    };
    struct {
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__5;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__5;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__5;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__5;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__4;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__4;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__4;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__4;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__3;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__3;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__3;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__3;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__2;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__2;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__2;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__2;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__1;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__1;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__1;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__1;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_he90314a2__0;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h693344ff__0;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h2b821f60__0;
        CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h82698da3__0;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_colours_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_colours_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_colours_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_colours_left;
        CData/*3:0*/ Brendan3_OneStep__DOT__choose__DOT__out_next_var;
        CData/*0:0*/ Brendan3_OneStep__DOT__choose__DOT__out_valid;
        QData/*53:0*/ Brendan3_OneStep__DOT__choose__DOT__pop_count;
        CData/*5:0*/ Brendan3_OneStep__DOT__choose__DOT__min_count;
        CData/*5:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT____Vlvbound_hfd3c7f52__0;
        QData/*53:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__out_pop_count;
        QData/*53:0*/ Brendan3_OneStep__DOT__choose__DOT__min_domain_inst__DOT__in_pop_count;
        CData/*5:0*/ Brendan3_OneStep__DOT__choose__DOT__min_domain_inst__DOT__out_min_count;
        QData/*53:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__in_pop_count;
        CData/*5:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__in_min_count;
        CData/*3:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__out_next_var;
        CData/*0:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__out_valid;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT____Vlvbound_h3e832cfe__0;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT____Vlvbound_h7930cb7c__0;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT____Vlvbound_h989d9e08__0;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT____Vlvbound_h608a81e7__0;
        CData/*3:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_variableId;
        CData/*3:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_tileId;
        CData/*1:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_rotation;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_colour_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_colour_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_colour_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_colour_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_elements_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_elements_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_elements_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_elements_left;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_colour_top;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_colour_right;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_colour_bottom;
        QData/*44:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_colour_left;
        CData/*0:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_colours_changed;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__piece_top;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__piece_right;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__piece_bottom;
        CData/*4:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__piece_left;
    };
    struct {
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_OUTW(out_domain_r0,80,0,3);
        VL_OUTW(out_domain_r1,80,0,3);
        VL_OUTW(out_domain_r2,80,0,3);
        VL_OUTW(out_domain_r3,80,0,3);
        VL_OUT16(out_unassigned_variables,8,0);
        VL_OUT16(out_unassigned_tiles,8,0);
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__out_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__out_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__out_unassigned_tiles;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_load_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_load_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_load_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_load_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_load_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_load_unassigned_tiles;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_prop1_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_prop1_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_prop1_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_prop1_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_prop1_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_prop1_unassigned_tiles;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_combined_domain;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_assign_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_assign_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_assign_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__w_assign_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_assign_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__w_assign_unassigned_tiles;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__out_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__out_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__out_unassigned_tiles;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h83e6e3f8__3;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h3d0f5190__3;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h0e20df20__3;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h5f7117e2__3;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h83e6e3f8__2;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h3d0f5190__2;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h0e20df20__2;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h5f7117e2__2;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h83e6e3f8__1;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h3d0f5190__1;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h5f7117e2__1;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h0e20df20__1;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h83e6e3f8__0;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h3d0f5190__0;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h0e20df20__0;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT____Vlvbound_h5f7117e2__0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_domain_r1;
    };
    struct {
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_unassignedVariables;
        SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__out_unassignedTiles;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__in_unassignedVariables;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__in_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__singletons;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__candidates;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__in_singletons;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__in_not_first_col;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__in_not_last_col;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__in_unassignedVariables;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__out_candidates;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__expanded;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__in_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__min_domain_inst__DOT__in_candidates;
        SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__in_candidates;
        SData/*8:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_unassigned_tiles;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__in_domain_r3;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_domain_r3;
        SData/*8:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_unassigned_variables;
        SData/*8:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__out_unassigned_tiles;
        SData/*8:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__tile_mask;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r0__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r1__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r2__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r3__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r0__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r1__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r2__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r3__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r0__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r1__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r2__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r3__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r0__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r1__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r2__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r3__0;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r0__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r1__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r2__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r3__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r0__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r1__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r2__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop1__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r3__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r0__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r1__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r2__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r3__1;
    };
    struct {
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r0__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r1__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r2__1;
        VlWide<3>/*80:0*/ __Vtrigprevexpr___TOP__Brendan3_OneStep__DOT__prop2__stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r3__1;
        IData/*31:0*/ Brendan3_OneStep__DOT__select_tile_and_rotation__DOT__unnamedblk1__DOT__t;
        IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__set_initial_constraints__DOT__unnamedblk1__DOT__id;
        IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__compute_domain_sizes__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__min_domain_inst__DOT__find_minimum_domain_size__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__select_next_variable__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__vid;
        IData/*31:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__tid;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__X = 1U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__A = 2U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__B = 4U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__C = 8U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__D = 0x10U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__BOUNDARY = 1U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__BORDER = 6U;
    static constexpr CData/*4:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__INNER_C = 0x18U;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__FIXED_CORNER = 1U;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__FREE_CORNER = 0x000eU;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__EDGE_D = 0x00f0U;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__INNER_D = 0x0100U;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__NOT_FIRST_COL = 0x01b6U;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__NOT_LAST_COL = 0x00dbU;
    static constexpr SData/*8:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__VALID_MASK = 0x01ffU;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__N = 3U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__CC = 5U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__N = 3U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__BORDER_COLOUR_COUNT = 2U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__INNER_COLOUR_COUNT = 2U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__CC = 5U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__CC = 5U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__elements__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__N = 3U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__BORDER_COLOUR_COUNT = 2U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__INNER_COLOUR_COUNT = 2U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__CC = 5U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__NUM_EDGES = 4U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__loader__DOT__initial_game__DOT__NUM_INNER = 1U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__N = 3U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__N = 3U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__expand_inst__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__domain_sizes_inst__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__min_domain_inst__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__choose__DOT__select_inst__DOT__ID_BITS = 4U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__N = 3U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__CC = 5U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__V = 9U;
    static constexpr IData/*31:0*/ Brendan3_OneStep__DOT__assign_inst__DOT__ID_BITS = 4U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
