// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_PROPAGATEONCE__N3_V9_C5_H_
#define VERILATED_VTOP_PROPAGATEONCE__N3_V9_C5_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_PropagateOnce__N3_V9_C5 final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        QData/*44:0*/ in_elements_top;
        QData/*44:0*/ in_elements_right;
        QData/*44:0*/ in_elements_bottom;
        QData/*44:0*/ in_elements_left;
        QData/*44:0*/ in_colours_top;
        QData/*44:0*/ in_colours_right;
        QData/*44:0*/ in_colours_bottom;
        QData/*44:0*/ in_colours_left;
        QData/*44:0*/ out_colours_top;
        QData/*44:0*/ out_colours_right;
        QData/*44:0*/ out_colours_bottom;
        QData/*44:0*/ out_colours_left;
        CData/*0:0*/ out_changed;
        CData/*0:0*/ out_deadend;
        QData/*44:0*/ w1_colours_top;
        QData/*44:0*/ w1_colours_right;
        QData/*44:0*/ w1_colours_bottom;
        QData/*44:0*/ w1_colours_left;
        CData/*0:0*/ w1_changed;
        CData/*0:0*/ w1_deadend;
        QData/*44:0*/ w2_colours_top;
        QData/*44:0*/ w2_colours_right;
        QData/*44:0*/ w2_colours_bottom;
        QData/*44:0*/ w2_colours_left;
        CData/*0:0*/ w2_updated;
        CData/*0:0*/ w2_deadend;
        CData/*0:0*/ w3_changed;
        CData/*0:0*/ w3_deadend;
        CData/*0:0*/ w4_changed;
        CData/*0:0*/ w4_deadend;
        CData/*0:0*/ w5_deadend;
        CData/*0:0*/ w6_deadend;
        CData/*0:0*/ w6_singleton;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_colours_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_colours_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_colours_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_colours_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_elements_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_elements_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_elements_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__in_elements_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__out_colours_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__out_colours_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__out_colours_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__out_colours_left;
        CData/*0:0*/ stage1_domain_to_colour__DOT__out_changed;
        CData/*0:0*/ stage1_domain_to_colour__DOT__out_deadend;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el0_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el0_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el0_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el0_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el1_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el1_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el1_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el1_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el2_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el2_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el2_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el2_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el3_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el3_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el3_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__el3_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__t0;
    };
    struct {
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__r0w;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__b0;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__l0;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__t1;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__r1w;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__b1;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__l1;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__t2;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__r2w;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__b2;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__l2;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__t3;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__r3w;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__b3;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__l3;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_top;
    };
    struct {
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_colour_left;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_left;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_colour_top;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_colour_right;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_colour_bottom;
        CData/*4:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_colour_left;
        CData/*4:0*/ stage2_cascade_colour__DOT____Vlvbound_h8b212d45__0;
        CData/*4:0*/ stage2_cascade_colour__DOT____Vlvbound_h596f0d3a__0;
        CData/*4:0*/ stage2_cascade_colour__DOT____Vlvbound_heb914163__0;
        CData/*4:0*/ stage2_cascade_colour__DOT____Vlvbound_h58c66825__0;
        QData/*44:0*/ stage2_cascade_colour__DOT__in_colours_top;
        QData/*44:0*/ stage2_cascade_colour__DOT__in_colours_right;
        QData/*44:0*/ stage2_cascade_colour__DOT__in_colours_bottom;
        QData/*44:0*/ stage2_cascade_colour__DOT__in_colours_left;
        QData/*44:0*/ stage2_cascade_colour__DOT__out_colours_top;
        QData/*44:0*/ stage2_cascade_colour__DOT__out_colours_right;
        QData/*44:0*/ stage2_cascade_colour__DOT__out_colours_bottom;
        QData/*44:0*/ stage2_cascade_colour__DOT__out_colours_left;
        CData/*0:0*/ stage2_cascade_colour__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__out_updated;
        CData/*3:0*/ stage2_cascade_colour__DOT__pair_deadend;
        CData/*3:0*/ stage2_cascade_colour__DOT__pair_updated;
        IData/*19:0*/ stage2_cascade_colour__DOT__pair_horizontal;
    };
    struct {
        IData/*19:0*/ stage2_cascade_colour__DOT__pair_vertical;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_slotRightColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_neighbourLeftColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_slotDownColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_neighbourUpColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_horizontalColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_verticalColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__horizontal_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__vertical_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__horizontal_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__vertical_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_slotRightColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_neighbourLeftColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_slotDownColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_neighbourUpColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_horizontalColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_verticalColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__horizontal_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__vertical_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__horizontal_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__vertical_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_slotRightColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_neighbourLeftColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_slotDownColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__in_neighbourUpColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_horizontalColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_verticalColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__out_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__horizontal_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__vertical_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__horizontal_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__vertical_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__in_neighbourColour;
    };
    struct {
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_slotRightColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_neighbourLeftColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_slotDownColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__in_neighbourUpColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_horizontalColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_verticalColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__out_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__horizontal_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__vertical_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__horizontal_updated;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__vertical_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__out_updated;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__in_slotColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__in_neighbourColour;
        CData/*4:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__out_combinedColour;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__out_deadend;
        CData/*0:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__out_updated;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_colours_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_colours_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_colours_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_colours_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_elements_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_elements_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_elements_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__in_elements_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__out_deadend;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el0_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el0_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el0_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el0_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el1_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el1_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el1_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el1_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el2_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el2_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el2_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el2_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el3_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el3_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el3_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__el3_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_colour_left;
    };
    struct {
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_colour_right;
    };
    struct {
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT____Vlvbound_hcdcdb015__0;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_colour_top;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_colour_right;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_colour_bottom;
        CData/*4:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_colour_left;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_top;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_right;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_bottom;
        QData/*44:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_element_left;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_changed;
        CData/*0:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_deadend;
        CData/*0:0*/ stage4_all_different__DOT__out_changed;
    };
    struct {
        CData/*0:0*/ stage4_all_different__DOT__out_deadend;
        CData/*0:0*/ stage5_tile_frequency__DOT__out_deadend;
        CData/*0:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_hb7504c00__1;
        CData/*0:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_hb7504c00__0;
        CData/*0:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_hb7504c00__1;
        CData/*0:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_hb7504c00__0;
        CData/*0:0*/ stage6_singleton_detection__DOT____Vlvbound_h9e5ebd43__0;
        CData/*0:0*/ stage6_singleton_detection__DOT____Vlvbound_h71e3b768__0;
        CData/*0:0*/ stage6_singleton_detection__DOT__out_singleton;
        CData/*0:0*/ stage6_singleton_detection__DOT__out_deadend;
        CData/*3:0*/ stage6_singleton_detection__DOT__detect_singletons_and_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__tile_id;
        CData/*1:0*/ stage6_singleton_detection__DOT__detect_singletons_and_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__rot;
        VlWide<3>/*80:0*/ in_domain_r0;
        VlWide<3>/*80:0*/ in_domain_r1;
        VlWide<3>/*80:0*/ in_domain_r2;
        VlWide<3>/*80:0*/ in_domain_r3;
        SData/*8:0*/ in_unassigned_variables;
        SData/*8:0*/ in_unassigned_tiles;
        VlWide<3>/*80:0*/ out_domain_r0;
        VlWide<3>/*80:0*/ out_domain_r1;
        VlWide<3>/*80:0*/ out_domain_r2;
        VlWide<3>/*80:0*/ out_domain_r3;
        SData/*8:0*/ out_unassigned_variables;
        SData/*8:0*/ out_unassigned_tiles;
        VlWide<3>/*80:0*/ w3_domain_r0;
        VlWide<3>/*80:0*/ w3_domain_r1;
        VlWide<3>/*80:0*/ w3_domain_r2;
        VlWide<3>/*80:0*/ w3_domain_r3;
        VlWide<3>/*80:0*/ w4_domain_r0;
        VlWide<3>/*80:0*/ w4_domain_r1;
        VlWide<3>/*80:0*/ w4_domain_r2;
        VlWide<3>/*80:0*/ w4_domain_r3;
        VlWide<3>/*80:0*/ w5_domain_r0;
        VlWide<3>/*80:0*/ w5_domain_r1;
        VlWide<3>/*80:0*/ w5_domain_r2;
        VlWide<3>/*80:0*/ w5_domain_r3;
        VlWide<3>/*80:0*/ stage1_domain_to_colour__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage1_domain_to_colour__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage1_domain_to_colour__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage1_domain_to_colour__DOT__in_domain_r3;
        SData/*8:0*/ stage1_domain_to_colour__DOT__v_changed;
        SData/*8:0*/ stage1_domain_to_colour__DOT__v_deadend;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_domain;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__in_domain_r3;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ stage3_colour_to_domain__DOT__out_domain_r3;
        SData/*8:0*/ stage3_colour_to_domain__DOT__v_changed;
        SData/*8:0*/ stage3_colour_to_domain__DOT__v_deadend;
    };
    struct {
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__in_domain;
        SData/*8:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__out_domain;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_hcbee8ed6__1;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_hf53730ae__1;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_hd5fdfdfa__1;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_h5748f8c4__1;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_hcbee8ed6__0;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_hf53730ae__0;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_hd5fdfdfa__0;
        SData/*8:0*/ stage4_all_different__DOT____Vlvbound_h5748f8c4__0;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__in_domain_r3;
        SData/*8:0*/ stage4_all_different__DOT__in_unassignedVariables;
        SData/*8:0*/ stage4_all_different__DOT__in_unassignedTiles;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ stage4_all_different__DOT__out_domain_r3;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__in_domain_r3;
        SData/*8:0*/ stage5_tile_frequency__DOT__in_unassigned_variables;
        SData/*8:0*/ stage5_tile_frequency__DOT__in_unassigned_tiles;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__out_domain_r3;
        VlWide<8>/*242:0*/ stage5_tile_frequency__DOT__wire_r0;
        VlWide<8>/*242:0*/ stage5_tile_frequency__DOT__wire_r1;
        VlWide<8>/*242:0*/ stage5_tile_frequency__DOT__wire_r2;
        VlWide<8>/*242:0*/ stage5_tile_frequency__DOT__wire_r3;
        SData/*8:0*/ stage5_tile_frequency__DOT__check_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__combined;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_hac10d104__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_h157d6e44__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_hb452bbc4__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_h378736b6__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_haf89d330__1;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_haf89d330__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_h07786676__1;
    };
    struct {
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT____Vlvbound_h07786676__0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_domain_r3;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_unassigned_variables;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__in_unassigned_tiles;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__out_domain_r3;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__tile_forced;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__forced_mask;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__var_mask;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__combined;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_hac10d104__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_h157d6e44__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_hb452bbc4__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_h378736b6__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_haf89d330__1;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_haf89d330__0;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_h07786676__1;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT____Vlvbound_h07786676__0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_domain_r3;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_unassigned_variables;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__in_unassigned_tiles;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__out_domain_r3;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__tile_forced;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__forced_mask;
        VlWide<3>/*80:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__var_mask;
        SData/*8:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__combined;
        SData/*8:0*/ stage6_singleton_detection__DOT____Vlvbound_h8ffe20da__0;
        SData/*8:0*/ stage6_singleton_detection__DOT____Vlvbound_h0983dcda__0;
        SData/*8:0*/ stage6_singleton_detection__DOT____Vlvbound_ha047ac56__0;
        SData/*8:0*/ stage6_singleton_detection__DOT____Vlvbound_h937e4710__0;
        SData/*8:0*/ stage6_singleton_detection__DOT__in_unassignedVariables;
        SData/*8:0*/ stage6_singleton_detection__DOT__in_unassignedTiles;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__in_domain_r0;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__in_domain_r1;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__in_domain_r2;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__in_domain_r3;
        SData/*8:0*/ stage6_singleton_detection__DOT__out_unassignedVariables;
        SData/*8:0*/ stage6_singleton_detection__DOT__out_unassignedTiles;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__out_domain_r0;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__out_domain_r1;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__out_domain_r2;
        VlWide<3>/*80:0*/ stage6_singleton_detection__DOT__out_domain_r3;
        SData/*8:0*/ stage6_singleton_detection__DOT__detect_singletons_and_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__combined;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__unnamedblk1__DOT__p;
    };
    struct {
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage2_cascade_colour__DOT__write_cascade_results_to_colour_arrays__DOT__unnamedblk1__DOT__py;
        IData/*31:0*/ stage2_cascade_colour__DOT__write_cascade_results_to_colour_arrays__DOT__unnamedblk1__DOT__unnamedblk2__DOT__px;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__apply_colour_to_domain_and_detect_change_deadend__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ stage4_all_different__DOT__apply_mask_to_active_variables__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ stage4_all_different__DOT__detect_changed_and_deadend__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__check_deadend__DOT__unnamedblk2__DOT__t;
        IData/*31:0*/ stage5_tile_frequency__DOT__check_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__cnt;
        IData/*31:0*/ stage5_tile_frequency__DOT__check_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__t;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__cnt;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__fv;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__build_variable_masks__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__build_variable_masks__DOT__unnamedblk5__DOT__unnamedblk6__DOT__t;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__apply_masks__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__t;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__cnt;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__fv;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__find_forced_tiles__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__build_variable_masks__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__build_variable_masks__DOT__unnamedblk5__DOT__unnamedblk6__DOT__t;
        IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__apply_masks__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ stage6_singleton_detection__DOT__detect_singletons_and_deadend__DOT__unnamedblk2__DOT__v;
        IData/*31:0*/ stage6_singleton_detection__DOT__detect_singletons_and_deadend__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__p;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr IData/*31:0*/ N = 3U;
    static constexpr IData/*31:0*/ V = 9U;
    static constexpr IData/*31:0*/ CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__id = 0U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__id = 1U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__id = 2U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__id = 3U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__id = 4U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__id = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__id = 6U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__id = 7U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__id = 8U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage1_domain_to_colour__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__PAIRS = 4U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__id = 0U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__p = 0U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__id = 1U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__p = 1U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__id = 3U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__p = 2U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__id = 4U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__p = 3U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__h_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__pair__DOT__v_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__h_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage2_cascade_colour__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__pair__DOT__v_cascade__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__id = 0U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__id = 1U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__id = 2U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__id = 3U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__id = 4U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__id = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__id = 6U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__id = 7U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__id = 8U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__0__KET____DOT__top_left__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__1__KET____DOT__top_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__0__KET____DOT__gen_x__BRA__2__KET____DOT__top_right__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__0__KET____DOT__left_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot0__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot1__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot2__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__1__KET____DOT__inner__DOT__rot3__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__1__KET____DOT__gen_x__BRA__2__KET____DOT__right_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__0__KET____DOT__bottom_left__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__1__KET____DOT__bottom_edge__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage3_colour_to_domain__DOT__gen_y__BRA__2__KET____DOT__gen_x__BRA__2__KET____DOT__bottom_right__DOT__rot__DOT__CC = 5U;
    static constexpr IData/*31:0*/ stage4_all_different__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage4_all_different__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__ITERATIONS = 2U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__0__KET____DOT__stage__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage5_tile_frequency__DOT__gen_stage__BRA__1__KET____DOT__stage__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage6_singleton_detection__DOT__N = 3U;
    static constexpr IData/*31:0*/ stage6_singleton_detection__DOT__V = 9U;
    static constexpr IData/*31:0*/ stage6_singleton_detection__DOT__ID_BITS = 4U;

    // CONSTRUCTORS
    Vtop_PropagateOnce__N3_V9_C5();
    ~Vtop_PropagateOnce__N3_V9_C5();
    void ctor(Vtop__Syms* symsp, const char* namep);
    void dtor();
    VL_UNCOPYABLE(Vtop_PropagateOnce__N3_V9_C5);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
